apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fdqk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-fdqk@sha256:6a938db1065df59a018d180720131b82ea4e8e68dc6304481a1f690b141fcea9
        name: my-nodejs
        resources: {}
status: {}
